# Generated by Django 4.0.4 on 2022-04-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand_id', models.CharField(max_length=255, unique=True)),
                ('year', models.IntegerField()),
                ('fuel', models.IntegerField()),
                ('price', models.FloatField()),
                ('elo', models.IntegerField()),
                ('probability_price_medium', models.FloatField()),
                ('probability_price_high', models.FloatField()),
                ('probability_price_low', models.FloatField()),
            ],
            options={
                'verbose_name': 'Motorcycle',
                'verbose_name_plural': 'Motorcycles',
            },
        ),
    ]
